### ISSUE TITLE
Krun makes two log files in reboot mode.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#216] opened 2016-06-20 14:33 UTC
In reboot mode, krun makes two log files, date-stamped exactly an hour apart. **EDIT** they are not an hour apart, sorry.

In the below pdb session, we can see this happening. There is a breakpoint in `attach_log_file`:

```
vext01@bencher2:~/research/warmup_experiment/krun/examples$ ../krun.py --fake-reboots --no-user-change --no-tickless-check --no-pstate-check example.krun  --reboot --quick
[2] > /home/vext01/research/warmup_experiment/krun/krun.py(337)attach_log_file()
-> log_filename = config.log_filename(resume)
(Pdb++) s                                                                                                                                           
--Call--
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(67)log_filename()
-> def log_filename(self, resume=False):
(Pdb++) s                                                                                                                                           
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(68)log_filename()
-> assert self.filename.endswith(".krun")
(Pdb++) s                                                                                                                                           
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(69)log_filename()
-> if resume:
(Pdb++) s                                                                                                                                           
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(73)log_filename()
-> tstamp = time.strftime(LOGFILE_FILENAME_TIME_FORMAT)
(Pdb++) n                                                                                                                                           
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(74)log_filename()
-> return self.filename[:-5] + "_%s.log" % tstamp
(Pdb++) tstamp                                                                                                                                      
'20160620_153017'
(Pdb++) c                                                                                                                                           
[2016-06-20 15:30:24 WARNING] Ignoring enabled P-states (--no-pstate-check)
[2016-06-20 15:30:24 INFO] Wait 1 secs to allow system to cool prior to collecting initial temperature readings
[2016-06-20 15:30:24 WARNING] SIMULATED: `time.sleep(1)` (--quick)
[2016-06-20 15:30:24 WARNING] Not changing user (--no-change-user)
[2016-06-20 15:30:24 WARNING] Not changing user (--no-change-user)
[2016-06-20 15:30:24 WARNING] Not changing user (--no-change-user)
[2016-06-20 15:30:24 INFO] Reboot prior to first execution
[2016-06-20 15:30:24 WARNING] SIMULATED: reboot (--fake-reboots)
[2] > /home/vext01/research/warmup_experiment/krun/krun.py(337)attach_log_file()
-> log_filename = config.log_filename(resume)
(Pdb++) s                                                                                                                                           
--Call--
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(67)log_filename()
-> def log_filename(self, resume=False):
(Pdb++) s
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(68)log_filename()
-> assert self.filename.endswith(".krun")
(Pdb++) 
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(69)log_filename()
-> if resume:
(Pdb++) n
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(70)log_filename()
-> config_mtime = time.gmtime(os.path.getmtime(self.filename))
(Pdb++) n
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(71)log_filename()
-> tstamp = time.strftime(LOGFILE_FILENAME_TIME_FORMAT, config_mtime)
(Pdb++) n
[3] > /home/vext01/research/warmup_experiment/krun/krun/config.py(74)log_filename()
-> return self.filename[:-5] + "_%s.log" % tstamp
(Pdb++) tstamp
'20160620_143024'
(Pdb++) c
[2016-06-20 15:32:56 WARNING] Ignoring enabled P-states (--no-pstate-check)
...
CTRL+C
vext01@bencher2:~/research/warmup_experiment/krun/examples$ ls *log
example_20160620_143024.log  example_20160620_153017.log
```

I wonder why we timestamp the log at all. The logic is quite involved, and we don't date-stamp the results file. It might be easier to emit the log to (e.g.) `example.log` if the config file was `example.krun`.

Thoughts.

**Comment by snim2** [comment] 2016-06-20 14:40
So, it looks like one of those calls to `Config.log_filename()` should have `resume` set to `True`...

**Comment by vext01** [comment] 2016-06-20 14:44
Are you able to reproduce? This was using the example config file?

**Comment by snim2** [comment] 2016-06-20 14:46
Not with fake reboots, will try with real reboots.

**Comment by vext01** [comment] 2016-06-20 14:56
I was using fake reboots on bencher2 above.

**Comment by snim2** [comment] 2016-06-20 15:17
OK, I can now reproduce this...

**Comment by vext01** [comment] 2016-06-20 15:18
What was different?

**Comment by snim2** [comment] 2016-06-20 15:18
I remembered `--fake-reboots` and forgot `--reboot`!

**Comment by snim2** [comment] 2016-06-20 16:18
OK, I have a fix for this now, will raise the PR

**Closed** 2016-06-21 11:36 UTC
Labels: bug
